name: Build and Release

on:
  push:
    branches: ['main']
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore GetCountries/GetCountries.csproj
      
      - name: Build project
        run: dotnet publish GetCountries/GetCountries.csproj -c Release -o publish-${{ matrix.os }} --self-contained true -r ${{ matrix.os == 'ubuntu-latest' && 'linux-x64' || matrix.os == 'macos-latest' && 'osx-x64' || 'win-x64' }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GetCountries-${{ matrix.os }}
          path: publish-${{ matrix.os }}/*
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/GetCountries-linux-x64/GetCountries
            artifacts/GetCountries-macos-x64/GetCountries
            artifacts/GetCountries-win-x64/GetCountries.exe
          token: ${{ secrets.PAT_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
