name: Build and Release

on:
  push:
    branches: ['main']
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore GetCountries/GetCountries.csproj
      
      - name: Build project
        run: dotnet publish GetCountries/GetCountries.csproj -c Release -o publish-${{ matrix.os }} --self-contained true -p:PublishSingleFile=true -r ${{ matrix.os == 'ubuntu' && 'linux-x64' || matrix.os == 'macos' && 'osx-x64' || 'win-x64' }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GetCountries-${{ matrix.os }}
          path: publish-${{ matrix.os }}/*
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
    
      - name: Rename
        run: |
          mv artifacts/GetCountries-ubuntu/GetCountries artifacts/GetCountries-ubuntu/GetCountries-linux 
          mv artifacts/GetCountries-macos/GetCountries artifacts/GetCountries-macos/GetCountries-macos 
          mv artifacts/GetCountries-windows/GetCountries.exe artifacts/GetCountries-windows/GetCountries-windows.exe 
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/GetCountries-ubuntu/GetCountries-linux
            artifacts/GetCountries-macos/GetCountries-macos
            artifacts/GetCountries-windows/GetCountries-windows.exe
          token: ${{ secrets.PAT_TOKEN }}
          tag_name: ${{ github.ref_name }}-${{ github.run_id }}
          name: Release ${{ github.ref_name }}-${{ github.run_id }}
          draft: false
          prerelease: false
