name: Build and Release

on:
  push:
    branches: ['main']
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore GetCountries/GetCountries.csproj
      
      - name: Build project
        run: dotnet publish GetCountries/GetCountries.csproj -c Release -o publish-${{ matrix.os }} --self-contained true -r ${{ matrix.os == 'ubuntu' && 'linux-x64' || matrix.os == 'macos' && 'osx-x64' || 'win-x64' }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GetCountries-${{ matrix.os }}
          path: publish-${{ matrix.os }}/*
  
  release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu
            artifact: GetCountries
            asset_name: GetCountries-linux
          - os: windows
            artifact: GetCountries.exe
            asset_name: GetCountries-windows
          - os: macos
            artifact: GetCountries
            asset_name: GetCountries-macos
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
    
      - name: Debug - List Files
        run: ls -R artifacts
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          file: artifacts/GetCountries-${{ matrix.os }}/${{ matrix.artifact }}
          asset_name: ${{ matrix.asset_name }}
          token: ${{ secrets.PAT_TOKEN }}
          tag_name: ${{ github.ref_name }}-${{ github.run_id }}
          name: Release ${{ github.ref_name }}-${{ github.run_id }}
          draft: false
          prerelease: false
